artifacts_root: artifacts  #artifacts means wht r the things we generating


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Bhoomika-gp/branch/raw/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion